### ISSUE TITLE
Student Progress Review 2

### ISSUE THREAD

**Issue by rodriguez03** [CMPSC-580-Allegheny-College-Spring-2024/exemplarproject-hayleepierce#3]
You did such an amazing job with implementation so far! Your repo is very organized and I see you have a clear vision on how you will tackle this project! I do have to mention that you have to ensure that you are following your steps accordingly and do not get caught up with the implementation of the project but also keep track of your documentation! Overall keep up the good work!

**Comment by hayleepierce** [comment]
Documentation is finished.
