### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by simojo** [CMPSC-580-Allegheny-College-Spring-2024/exemplarproject-hayleepierce#4]
Hi Haylee!

Great work on your tool that searches academic articles. There are endless applications for such a tool. May I suggest that you begin to fix the function that removes words with less than four characters? That seemed to cause some issues in your demonstration!! Good luck!!

Thanks,
Simon

**Comment by hayleepierce** [comment]
Thank _you_, for revealing this issue. I need a better way to remove stop words in general. I'm going to try to use [nltk](https://www.geeksforgeeks.org/removing-stop-words-nltk-python/) for this process.

**Comment by hayleepierce** [comment]
I've fixed this issue.
